name: wind-prod
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bokeh=2.4.3
  - boto3=1.24.26
  - botocore=1.27.26
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - cffi=1.15.0
  - cftime=1.5.1.1
  - charset-normalizer=2.1.0
  - click=8.1.3
  - cloudpickle=2.1.0
  - cryptography=35.0.0
  - curl=7.82.0
  - cytoolz=0.11.2
  - dask=2022.7.0
  - dask-core=2022.7.0
  - distributed=2022.7.0
  - freetype=2.10.4
  - fsspec=2022.5.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.1.0
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libwebp-base=1.2.2
  - libzip=1.8.0
  - locket=1.0.0
  - lz4=4.0.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - msgpack-python=1.0.3
  - ncurses=6.3
  - netcdf4=1.5.7
  - nomkl=1.0
  - numexpr=2.8.0
  - numpy=1.22.3
  - olefile=0.46
  - openssl=1.1.1p
  - packaging=21.3
  - pandas=1.4.2
  - partd=1.2.0
  - pillow=7.2.0
  - pip=22.1.2
  - psutil=5.9.1
  - pycparser=2.21
  - pymongo=4.1.1
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-dotenv=0.20.0
  - python_abi=3.9
  - pytz=2022.1
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.28.1
  - s3transfer=0.6.0
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - setuptools=61.2.0
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.38.5
  - tblib=1.7.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.1
  - typing_extensions=4.3.0
  - tzdata=2022a
  - urllib3=1.26.10
  - wheel=0.37.1
  - windpowerlib=0.2.1
  - xarray=2022.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.2.0
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - awslambdaric==2.0.4
    - simplejson==3.17.2
